services:
  Netzmacht\ContaoWorkflowExampleBundle\Workflow\Type\ExampleType:
    tags:
      - { name: 'netzmacht.contao_workflow.type' }

  Netzmacht\ContaoWorkflowExampleBundle\Workflow\Action\PublishActionFactory:
    arguments:
      - '@netzmacht.contao_workflow.property_access_manager'
    tags:
      - { name: 'netzmacht.contao_workflow.action' }

  Netzmacht\ContaoWorkflowExampleBundle\Workflow\Action\SendEmailNotificationFactory:
    arguments:
      - '@mailer'
    tags:
      - { name: 'netzmacht.contao_workflow.action' }

  Netzmacht\ContaoWorkflowExampleBundle\Workflow\Form\SendEmailNotificationFormBuilder:
    tags:
      - { name: 'netzmacht.contao_workflow.action_form_builder'}

  Netzmacht\ContaoWorkflowExampleBundle\EventListener\ExampleDcaListener:
    public: true
    arguments:
      - '@netzmacht.contao_toolkit.dca.manager'
      - '@translator'
